sudo: required

dist: trusty

language: node_js

node_js:
  - 9

cache:
  yarn: true
  directories:
    - node_modules
    - app/node_modules
    - flow-typed
    - $(npm config get prefix)/lib/node_modules
    - $HOME/.electron

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - icnsutils
      - graphicsmagick
      - xz-utils
      - gcc-multilib
      - g++-multilib
      - rpm
      - libavahi-compat-libdnssd-dev

before_install: yarn global add greenkeeper-lockfile@1

install:
  - export CXX="g++-4.8"
  - yarn
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3
  - greenkeeper-lockfile-update

script:
  # - yarn lint
  # - yarn test
  - yarn package-ci
  - yarn test-e2e

after_script: greenkeeper-lockfile-upload
