os: unstable

environment:
  matrix:
    - nodejs_version: 8

cache:
  - "%LOCALAPPDATA%/Yarn"
  - node_modules -> yarn.lock
  - app/node_modules -> app/yarn.lock

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - yarn
  - cd app && yarn

test_script:
  - npm run test
  - npm run package
  - npm run test-e2e
