environment:
  matrix:
    - nodejs_version: 6

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm install -g npm@latest --loglevel=warn
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install --loglevel=warn

test_script:
  - node --version
  - npm --version
  - npm run test
  - npm run bench-api
  # - npm run test-screenshot
