platform:
  - x64

image: Visual Studio 2017

environment:
  nodejs_version: 11
  BONJOUR_SDK_HOME: 'C:\\Program Files\\Bonjour SDK'

cache:
  - "%LOCALAPPDATA%/Yarn"
  - node_modules -> yarn.lock
  - app/node_modules -> app/yarn.lock
  - flow-typed
  - '%LOCALAPPDATA%\electron\Cache'
  - '%LOCALAPPDATA%\electron-builder\cache'

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version x64
  - set CI=true
  # Bonjour
  - appveyor DownloadFile https://www.samuelattard.com/files/bonjourcore2.msi
  - msiexec /i bonjourcore2.msi /qn
  - del bonjourcore2.msi
  - appveyor DownloadFile https://www.samuelattard.com/files/bonjoursdksetup.exe
  - bonjoursdksetup.exe /quiet
  - del bonjoursdksetup.exe
  # Install dependencies
  - yarn

test_script:
  - yarn lint
  # - yarn test
  - yarn package-ci
  - yarn build-e2e
  - yarn test-e2e --quarantine-mode
