os: unstable

environment:
  matrix:
    - nodejs_version: 8

cache:
  - "%LOCALAPPDATA%/Yarn"
  - node_modules -> package.json
  - app/node_modules -> app/package.json

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  # Bonjour
  - appveyor DownloadFile https://www.samuelattard.com/files/bonjourcore2.msi
  - msiexec /i bonjourcore2.msi /qn
  - del bonjourcore2.msi
  - appveyor DownloadFile https://www.samuelattard.com/files/bonjoursdksetup.exe
  - bonjoursdksetup.exe /quiet
  - del bonjoursdksetup.exe
  # Install npm dependencies
  - yarn
  - cd app && yarn

test_script:
  # - npm run lint
  # - npm run test
  - npm run package
  - npm run test-e2e
